name: rss-summarize-telegram-bot

services:
  rss-summarize-telegram-bot:
    container_name: rss-summarize-telegram-bot
    build: https://github.com/simonmysun/rss-summarize-telegram-bot.git
    init: true
    volumes:
      - /path/to/.env:/app/.env:r
      - /path/to/prompt_template.txt:/app/prompt_template.txt:r
    restart: unless-stopped
